[package]
name = "win_rs_playground"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.62.2", features = [
    "Globalization",
    "Storage_Streams",
]}
windows-future = "0.3.2"

